# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
       - uses: actions/checkout@v3
       - name: Set up Python 3.10
         uses: actions/setup-python@v3
         with:
           python-version: "3.10"
       - name: Install Python dependencies
         uses: py-actions/py-dependency-install@v4
         with:
           path: "requirements.txt"
       - name: Run pytest
         run: | 
           python -m pytest -v tests/test_runium.py::TestStartIn::test_processing